# Site settings
title: Nimble River
email: hello@nimbleriver.com
phone: 513.515.7977
description: "Independent IT consultant interested in automated processes and streamlining workflows. <br/> Have an idea for a new product? We'd love to listen and collaborate with you to see  what we can accomplish. Contact us and let's discuss your idea over coffee."
baseurl: ""
url: "http://nimbleriver.com"

team:
  - jeremy:
    twitter_username: jeremykahne
    github_username:  jkahne
    linkedin_username:  jeremykahne

# Build settings
markdown: kramdown
permalink: pretty
